version: "3.9"

services:
  tradingportal:
    build:
      context: ./src/YourBank.Infrastructure.TradingPortal
      dockerfile: Dockerfile # Removed incorrect ./
      args:
        APP_UID: ${APP_UID}
    container_name: yourbank_tradingportal
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "5000:80"
    depends_on:
      - identityservice
      - tradinggateway

  tradinggateway:
    build:
      context: ./src/YourBank.Infrastructure.TradingGateway
      dockerfile: Dockerfile
      args:
        APP_UID: ${APP_UID}
    container_name: yourbank_tradinggateway
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "5001:80"
    depends_on:
      - identityservice

  identityservice:
    build:
      context: ./src/YourBank.Infrastructure.IdentityService
      dockerfile: Dockerfile
      args:
        APP_UID: ${APP_UID}
    container_name: yourbank_identityservice
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "5002:80"

  pricingengine:
    build:
      context: ./src/YourBank.Infrastructure.PricingEngine
      dockerfile: Dockerfile
      args:
        APP_UID: ${APP_UID}
    container_name: yourbank_pricingengine
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "5003:80"

  ordermanagement:
    build:
      context: ./src/YourBank.Infrastructure.OrderManagement
      dockerfile: Dockerfile
      args:
        APP_UID: ${APP_UID}
    container_name: yourbank_ordermanagement
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "5004:80"
    depends_on:
      - identityservice
      - pricingengine

  orderexecution:
    build:
      context: ./src/YourBank.Infrastructure.OrderExecution
      dockerfile: Dockerfile
      args:
        APP_UID: ${APP_UID}
    container_name: yourbank_orderexecution
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "5005:80"
    depends_on:
      - ordermanagement

  postexecutionmonitoring:
    build:
      context: ./src/YourBank.Infrastructure.PostExecutionMonitoring
      dockerfile: Dockerfile
      args:
        APP_UID: ${APP_UID}
    container_name: yourbank_postexecutionmonitoring
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "5006:80"
    depends_on:
      - orderexecution
