#version: '3.8'

services:
  tradingportal:
    build:
      context: .
      dockerfile: src/TradingPortal.BlazorServer/Dockerfile
    ports:
      - "5000:443"          # host → container
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/certificates/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=YourPassword123
    volumes:
      - ./keys:/keys
      - .certificates/aspnetapp.pfx:/certificates/aspnetapp.pfx:ro
