version: "3.9"

services:
  tradingportal:
    build:
      context: ./src/tradingportal.blazor
      dockerfile: Dockerfile
      args:
        app_uid: ${app_uid}
    container_name: yourbank_tradingportal
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "5000:443"   # UI over HTTPS
    volumes:
      - ~/.aspnet/https:/https:ro

  apigateway:
    build:
      context: ./src/apigateway
      dockerfile: Dockerfile
      args:
        APP_UID: ${APP_UID}
    container_name: yourbank_apigateway
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "5001:443"
    volumes:
      - ~/.aspnet/https:/https:ro # mount the HTTPS certificate

  identityservice:
    build:
      context: ./src/identityservice
      dockerfile: Dockerfile
      args:
        APP_UID: ${APP_UID}
    container_name: yourbank_identityservice
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "5002:443"
    volumes:
      - ~/.aspnet/https:/https:ro

  tradingservice:
    build:
      context: ./src/tradingservice
      dockerfile: Dockerfile
      args:
        APP_UID: ${APP_UID}  
    container_name: yourbank_tradingservice
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "5003:80"

  riskservice:
    build:
      context: ./src/riskservice
      dockerfile: Dockerfile
      args:
        APP_UID: ${APP_UID}  
    container_name: yourbank_riskservice
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "5004:80"


  # pricingengine:
  #   build:
  #     context: ./src/PricingEngineService
  #     dockerfile: Dockerfile
  #     args:
  #       APP_UID: ${APP_UID}
  #   container_name: yourbank_pricingengine
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Production
  #   ports:
  #     - "5003:80"

 

  # orderexecution:
  #   build:
  #     context: ./src/Infrastructure.OrderExecution
  #     dockerfile: Dockerfile
  #     args:
  #       APP_UID: ${APP_UID}
  #   container_name: yourbank_orderexecution
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Production
  #   ports:
  #     - "5005:80"

  # postexecutionmonitoring:
  #   build:
  #     context: ./src/PostExecutionMonitoringService
  #     dockerfile: Dockerfile
  #     args:
  #       APP_UID: ${APP_UID}
  #   container_name: yourbank_postexecutionmonitoring
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Production
  #   ports:
  #     - "5006:80"
