version: "3.9"
services:
  identityservice:
    build:
      context: ./src/YourBank.IdentityService
      dockerfile: Dockerfile
    container_name: yourbank_identityservice
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "5000:80"

  pricingengine:
    build:
      context: ./src/YourBank.PricingEngine
      dockerfile: Dockerfile
    container_name: yourbank_pricingengine
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "5001:80"

  ordermanagement:
    build:
      context: ./src/YourBank.OrderManagement
      dockerfile: Dockerfile
    container_name: yourbank_ordermanagement
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "5002:80"

  orderexecution:
    build:
      context: ./src/YourBank.OrderExecution
      dockerfile: Dockerfile
    container_name: yourbank_orderexecution
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "5003:80"

  postexecutionmonitoring:
    build:
      context: ./src/YourBank.PostExecutionMonitoring
      dockerfile: Dockerfile
    container_name: yourbank_postexecutionmonitoring
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "5004:80"

  tradinggateway:
    build:
      context: ./src/YourBank.TradingGateway
      dockerfile: Dockerfile
    container_name: yourbank_tradinggateway
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "5005:80"
