@YourBank.Infrastructure.PostExecutionMonitoring_HostAddress = http://localhost:5262

GET {{YourBank.Infrastructure.PostExecutionMonitoring_HostAddress}}/weatherforecast/
Accept: application/json

###
