@BaseAddress = https://localhost:5001  
@Token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzMGIyZjE0Mi1jZWMyLTQyYjctODUxZC1lZWUyNGQxYjAwOGIiLCJlbWFpbCI6ImFsaWNlQGV4YW1wbGUuY29tIiwiZXhwIjoxNzUxNDczNTAyLCJpc3MiOiJodHRwczovL2xvY2FsaG9zdDo1MTAxIiwiYXVkIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NTEwMSJ9.Rl4MfwlqlNa7dLePZ4XTNDjeeZJAZY2ALo8orQavUXc

### Register a new user
POST {{BaseAddress}}/auth/register
Content-Type: application/json
{
  "email": "alice@example.com",
  "password": "P@ssw0rd!"
}

### Login with that user
POST {{BaseAddress}}/auth/login
Content-Type: application/json
{
  "email": "alice@example.com",
  "password": "P@ssw0rd!"
}


### anonymus ping
GET {{BaseAddress}}/ping


### authorized secureping 
GET {{BaseAddress}}/sping
Authorization: Bearer {{token}}
